### ISSUE TITLE
autoupdate pre-commit dependencies

### ISSUE THREAD

**Issue by FoSix** [PaloAltoNetworks/terraform-modules-vmseries-ci-workflows#32]
- [x] do python script
- [x] do [CI for PRs](https://github.com/PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/pull/34)
- [x] create the actual CI in the code repo after the above one gets merged
- [x] test how to move the information from `peter-evans/create-pull-request` about branch creation to a separate job
- [x] move the update pre-commit to a separate sub-workflow
- [x] get a better text in the PR body
- [x] figure out if we need all requirements in _pre_commit.yml sub workflow
- [x] re-do the way we manage python dependencies in workflows so that they can be updated with `dependabot`

**Comment by FoSix** [comment]
The only slight problem with is that when machine-writing a YAML file we get a slightly different format. Not really controllable. Not a big deal, but still different.

<details>
<summary>old format</summary>

```yaml
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.68.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt 
      - id: terraform_docs
        args: ['--args=--lockfile=false']
      - id: terraform_tflint
        args: [
          --args=--only=terraform_deprecated_interpolation,
          --args=--only=terraform_deprecated_index,
          --args=--only=terraform_module_pinned_source,
          --args=--only=terraform_naming_convention,
          --args=--only=terraform_workspace_remote,
        ]
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '2.2.125'
    hooks:
    - id: checkov
      verbose: true
      args: [--soft-fail]
```

</details>

<details>
<summary>new, machine, format</summary>

```yaml
repos:
- hooks:
  - id: terraform_fmt
  - args:
    - --args=--lockfile=false
    id: terraform_docs
  - args:
    - --args=--only=terraform_deprecated_interpolation
    - --args=--only=terraform_deprecated_index
    - --args=--only=terraform_module_pinned_source
    - --args=--only=terraform_naming_convention
    - --args=--only=terraform_workspace_remote
    id: terraform_tflint
  repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.79.1
- hooks:
  - args:
    - --soft-fail
    id: checkov
    verbose: true
  repo: https://github.com/bridgecrewio/checkov
  rev: 2.3.259
```

</details>
